### PR TITLE
Fix line maximum line length when scores are shown

### PR DESCRIPTION
**Pull request by neuschaefer**

### CODE REVIEW

**Comment by ohjames** [comment]
See https://github.com/jhawthorn/fzy/pull/46#issuecomment-320295466

**Comment by neuschaefer** [comment]
Feel free to merge this bugfix into your fork.

**Comment by jhawthorn** [comment]
@ohjames this project is active when I have the time, please quit posting this in every PR

**Comment by jhawthorn** [comment]
Thank you!

**Comment by neuschaefer** [comment]
There is another problem in the code: If the terminal is less than eight columns wide (which is hopefully a rare case for most users), then the score will be printed anyway, overflowing every result line. I think this can be fixed with a simple `&& maxwidth >= 9`. (Why 9? Because of the `$` that indicates that the result string has been cut off)

**Pull request merged**
