### PR TITLE
[WIP] Cursor movement in tty

### PR DESCRIPTION
**Pull request by b4b4r07**
Hi, I really like this awesome fuzzy finder!

I added cursor member to `tty_interface_t` struct to implement cursor movement.

Like this:

Support keybindings: Ctrl-A,Ctrl-E,`←`,`→`

TODO:
- [ ] append search (in string)
- [ ] delete char (in string)

How do you feel about this feature and implementation?

### CODE REVIEW

**Comment by jhawthorn** [comment]
:+1: I really like this and this seems like a good start

**Comment by b4b4r07** [comment]
@jhawthorn Thank you for your reply! Although it may take time, I want to improve it little by little.

**Comment by keith** [comment]
Ah I just noticed this PR after writing another implementation of this. Mine seems to be fully functional and can be found here https://github.com/jhawthorn/fzy/pull/46

**Comment by jhawthorn** [comment]
Closing for #46. Thanks!

**Pull request closed without merging**
