### PR TITLE
Add MSYS2 to the install instructions

### PR DESCRIPTION
**Pull request by ErichDonGubler**
That's right, it compiles and it's now available! :)

### CODE REVIEW

**Comment by jesse23** [comment]
@ErichDonGubler when I try to use this feature in both `msys bash` and `conEmu`. I get nothing and the UI will get stuck after a simple `ls -l|fzy`. Can you please help? Thanks.

**Comment by ErichDonGubler** [comment]
@jesse23: Where are you getting the `fzy` binary from?

**Comment by jesse23** [comment]
@ErichDonGubler  `pacman -S fzy` in the latest `msys2`

**Comment by ErichDonGubler** [comment]
@jesse23 Could you give me some repro and environment information? I definitely want `fzy` to be as usable as possible on a platform like MSYS2 -- you said you've used this in ConEmu and `msys bash` (which I assume to mean MinTTY)?

If the latter is true, that's interesting...because I originally did my testing and package creation with MinTTY itself:

mintty_fzy_test

**Comment by ErichDonGubler** [comment]
@jesse23: Just installed ConEmu and used the `msys2-64` preset...and it seems to work just fine. Do you have some configuration that's different from a preset?

**Comment by jesse23** [comment]
@ErichDonGubler  Many thanks for looking at this issue.

Yes I think it maybe caused by `conemu-msys2-64.exe`. ([link](https://conemu.github.io/en/CygwinMsysConnector.html]=))

Below is my configuration:
https://github.com/jesse23/dev_home/blob/master/conEmu/ConEmu.xml

My conEmu version is `ConEmu 171025 [64]`

I start my session with {{Bash:MSYS2}} in this config.

I will try to run it in clean machine later to verify it.

**Comment by ErichDonGubler** [comment]
I don't have access to a Windows machine this Thanksgiving weekend, but I'll try to take a look at this next week. :) I hope I can repro the issue!

**Comment by ErichDonGubler** [comment]
Let's move this discussion to https://github.com/ErichDonGubler/fzy/issues/2, since it doesn't really fit the scope of this PR. I will move details from here to there when I take a closer look.

**Comment by jhawthorn** [comment]
Can/should we combine this with the Arch Linux section?

MSYS2 is news to me but it's inclusion of pacman is awesome and I will give it a try next time I'm in my windows partition.

**Comment by ErichDonGubler** [comment]
@jhawthorne: That also makes sense to me. Seeing as the install instructions are so similar, I wouldn't mind just rename the Arch Linux section to also include MSYS2.

**Comment by jhawthorn** [comment]
Merged as 47609dbf73789bc28289576a12177965c04ef49b. Hope that looks good.

**Pull request closed without merging**
